# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cit/imvu/slurp-project/libslave

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cit/imvu/slurp-project/libslave

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"runtime\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cit/imvu/slurp-project/libslave/CMakeFiles /home/cit/imvu/slurp-project/libslave/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cit/imvu/slurp-project/libslave/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named slave

# Build rule for target.
slave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slave
.PHONY : slave

# fast build rule for target.
slave/fast:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/build
.PHONY : slave/fast

#=============================================================================
# Target rules for targets named slave-st

# Build rule for target.
slave-st: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slave-st
.PHONY : slave-st

# fast build rule for target.
slave-st/fast:
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/build
.PHONY : slave-st/fast

#=============================================================================
# Target rules for targets named slave_test

# Build rule for target.
slave_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 slave_test
.PHONY : slave_test

# fast build rule for target.
slave_test/fast:
	$(MAKE) -f CMakeFiles/slave_test.dir/build.make CMakeFiles/slave_test.dir/build
.PHONY : slave_test/fast

Slave.o: Slave.cpp.o
.PHONY : Slave.o

# target to build an object file
Slave.cpp.o:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/Slave.cpp.o
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/Slave.cpp.o
.PHONY : Slave.cpp.o

Slave.i: Slave.cpp.i
.PHONY : Slave.i

# target to preprocess a source file
Slave.cpp.i:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/Slave.cpp.i
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/Slave.cpp.i
.PHONY : Slave.cpp.i

Slave.s: Slave.cpp.s
.PHONY : Slave.s

# target to generate assembly for a file
Slave.cpp.s:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/Slave.cpp.s
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/Slave.cpp.s
.PHONY : Slave.cpp.s

collate.o: collate.cpp.o
.PHONY : collate.o

# target to build an object file
collate.cpp.o:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/collate.cpp.o
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/collate.cpp.o
.PHONY : collate.cpp.o

collate.i: collate.cpp.i
.PHONY : collate.i

# target to preprocess a source file
collate.cpp.i:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/collate.cpp.i
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/collate.cpp.i
.PHONY : collate.cpp.i

collate.s: collate.cpp.s
.PHONY : collate.s

# target to generate assembly for a file
collate.cpp.s:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/collate.cpp.s
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/collate.cpp.s
.PHONY : collate.cpp.s

field.o: field.cpp.o
.PHONY : field.o

# target to build an object file
field.cpp.o:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/field.cpp.o
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/field.cpp.o
.PHONY : field.cpp.o

field.i: field.cpp.i
.PHONY : field.i

# target to preprocess a source file
field.cpp.i:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/field.cpp.i
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/field.cpp.i
.PHONY : field.cpp.i

field.s: field.cpp.s
.PHONY : field.s

# target to generate assembly for a file
field.cpp.s:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/field.cpp.s
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/field.cpp.s
.PHONY : field.cpp.s

slave_log_event.o: slave_log_event.cpp.o
.PHONY : slave_log_event.o

# target to build an object file
slave_log_event.cpp.o:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/slave_log_event.cpp.o
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/slave_log_event.cpp.o
.PHONY : slave_log_event.cpp.o

slave_log_event.i: slave_log_event.cpp.i
.PHONY : slave_log_event.i

# target to preprocess a source file
slave_log_event.cpp.i:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/slave_log_event.cpp.i
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/slave_log_event.cpp.i
.PHONY : slave_log_event.cpp.i

slave_log_event.s: slave_log_event.cpp.s
.PHONY : slave_log_event.s

# target to generate assembly for a file
slave_log_event.cpp.s:
	$(MAKE) -f CMakeFiles/slave.dir/build.make CMakeFiles/slave.dir/slave_log_event.cpp.s
	$(MAKE) -f CMakeFiles/slave-st.dir/build.make CMakeFiles/slave-st.dir/slave_log_event.cpp.s
.PHONY : slave_log_event.cpp.s

test/test.o: test/test.cpp.o
.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/slave_test.dir/build.make CMakeFiles/slave_test.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i
.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/slave_test.dir/build.make CMakeFiles/slave_test.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s
.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/slave_test.dir/build.make CMakeFiles/slave_test.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... slave"
	@echo "... slave-st"
	@echo "... slave_test"
	@echo "... Slave.o"
	@echo "... Slave.i"
	@echo "... Slave.s"
	@echo "... collate.o"
	@echo "... collate.i"
	@echo "... collate.s"
	@echo "... field.o"
	@echo "... field.i"
	@echo "... field.s"
	@echo "... slave_log_event.o"
	@echo "... slave_log_event.i"
	@echo "... slave_log_event.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

